### ISSUE TITLE
Growatt Server HACS not visible in HACS console

### ISSUE THREAD

**Issue by NosNL** [muppet3000/homeassistant-growatt_server_api#1]
Please help .. i cannot find the Growatt Server HACS in HACS (see pic)
![Schermafbeelding 2023-01-05 121319](https://user-images.githubusercontent.com/55826688/210767285-e0b8ebac-77bd-4f99-9d47-d2c28d27a8b3.png)

ps.. good work so far 👍

**Comment by muppet3000** [comment]
WOW - You're keen! I haven't got this published to the HACS repo yet. I'll update this ticket when it's available.

If you want to test in the meantime you can add it as a custom repository and add it manually.

I haven't finished testing it yet though, I'd recommend waiting a few more days until there's a full release.

**Comment by erwinhasen** [comment]
FYI

I add it as a custom repository like you said.
Install is successful and it does accept my credentials but it does not discover any devices.
I will check again in a few days :)

Get the following log info.
Logger: homeassistant.setup
Source: setup.py:338
First occurred: 2:14:52 PM (2 occurrences)
Last logged: 2:19:12 PM

Unable to prepare setup for platform growatt_server_hacs.sensor: Platform not found (cannot import name 'UnitOfElectricCurrent' from 'homeassistant.const' (/usr/src/homeassistant/homeassistant/const.py)).

**Comment by muppet3000** [comment]
> FYI
> 
> I add it as a custom repository like you said. Install is successful and it does accept my credentials but it does not discover any devices. I will check again in a few days :)
> 
> Get the following log info. Logger: homeassistant.setup Source: setup.py:338 First occurred: 2:14:52 PM (2 occurrences) Last logged: 2:19:12 PM
> 
> Unable to prepare setup for platform growatt_server_hacs.sensor: Platform not found (cannot import name 'UnitOfElectricCurrent' from 'homeassistant.const' (/usr/src/homeassistant/homeassistant/const.py)).

A few comments here:

1. Currently there is nothing different between this integration and the one that's part of Home Assistant, in fact the one in Home Assistant is better because it's already pre-installed and is known to work
2. The issue you're having is that you're not running with the latest version of HomeAssistant. The latest release of the integration requires 2023.1.0
3. If you're trying to use this integration because the one in Home Assistant isn't working then you should just upgrade to 2023.1.0 as that also contains the fix for the bug in the Growatt integration

I'm hoping to have this repo up and running by the end of the week but it depends on how much progress I make in my spare time.
In the meantime I'll update the README files to reflect that this is a Work-in-Progress.

**Comment by erwinhasen** [comment]
> > FYI
> > I add it as a custom repository like you said. Install is successful and it does accept my credentials but it does not discover any devices. I will check again in a few days :)
> > Get the following log info. Logger: homeassistant.setup Source: setup.py:338 First occurred: 2:14:52 PM (2 occurrences) Last logged: 2:19:12 PM
> > Unable to prepare setup for platform growatt_server_hacs.sensor: Platform not found (cannot import name 'UnitOfElectricCurrent' from 'homeassistant.const' (/usr/src/homeassistant/homeassistant/const.py)).
> 
> A few comments here:
> 
> 1. Currently there is nothing different between this integration and the one that's part of Home Assistant, in fact the one in Home Assistant is better because it's already pre-installed and is known to work
> 2. The issue you're having is that you're not running with the latest version of HomeAssistant. The latest release of the integration requires 2023.1.0
> 3. If you're trying to use this integration because the one in Home Assistant isn't working then you should just upgrade to 2023.1.0 as that also contains the fix for the bug in the Growatt integration
> 
> I'm hoping to have this repo up and running by the end of the week but it depends on how much progress I make in my spare time. In the meantime I'll update the README files to reflect that this is a Work-in-Progress.

My bad, Gui did not show any updates available. had to update via terminal.
Now everything works.  thanks. (using the HACS repository version)

**Comment by muppet3000** [comment]
@NosNL  @erwinhasen - Just so you both know, I have changed the name of this repo in accordance with recommendations I've had from some of the upstream HACS repos. It may change again - sorry if it does.
This may mean that you need to add the custom repo again.

**Comment by NosNL** [comment]
No problem!! Monday i have time to look

By the way... The standard intergration works fine now

**Comment by muppet3000** [comment]
Hi Guys, 
I've now officially released what I had in the repo as the 1.0.0 release.
This week I'm going to start working on other new features for this repo, so wanted to get something out there that was identical to what was already live.

I'm still waiting on my PR to be merged that will add this repo to the default HACS repos, once that's merged then it will appear by default and you won't need to add it as a custom repo.

**Comment by NosNL** [comment]
Hello,

Do HACS working wel? are you able to change code and upload it direct to repo? (zo HACS change intergration in HA)

**Comment by muppet3000** [comment]
Hi @NosNL - I'm really sorry but I don't think I understand what you're asking. 
Are you asking if I can get this uploaded to the HACS default repo so that we don't need a custom repo?

**Comment by NosNL** [comment]
sorry.. my english is not so good.
my question is: 
you can adjust the code with HACS tool on your own initiative.. this adjustment will then automatically be applied to my installation
is this correct?

**Comment by muppet3000** [comment]
No need to apologise, your English is far better than any other language I can speak!
I now understand what you're asking though, thank you for the response.
I can't make it automatically update, however you will be notified in HACS whenever there is a new release available. You can't make it automatically update because it requires Home Assistant to be restarted for that to happen.

**Comment by NosNL** [comment]
thanks for your clear explanation

**Comment by NosNL** [comment]
i see now the  'Custom repositories' (adjustment completely missed)

can use in the HACS solution along the "standard" integration?

**Comment by muppet3000** [comment]
You can't use both at the same time as they'll use the same credentials and update the same sensors. 

You can just delete the old integration:
![image](https://user-images.githubusercontent.com/10612068/211795019-98ff0a29-2860-419c-b32c-3b26799aee0e.png)

Then configure the new one:
![image](https://user-images.githubusercontent.com/10612068/211795414-7b5d280e-8dae-42c8-a276-ec88b87fb2a7.png)

Once you've done that it should work and it will update all of the same sensors:
![image](https://user-images.githubusercontent.com/10612068/211795474-727895ed-b19b-4820-b79d-3e77452ab957.png)

If it doesn't work for any reason just delete the new integration and go back to using the old one.

**Comment by NosNL** [comment]
thanks for the support

i understand the working of HACS (constuction)

**Comment by NosNL** [comment]
it works perfect

please close this case

**Comment by muppet3000** [comment]
Thanks @NosNL I'm going to leave it open until the repo has been added to the default HACS repos which I have a PR for here: https://github.com/hacs/default/pull/1660
Hopefully once that's merged this will be even simpler to install and use.

**Comment by muppet3000** [comment]
Closing this ticket, it will never be added to HACS.
