### ISSUE TITLE
BUG - Expected data source not listed in power dashboard

### ISSUE THREAD

**Issue by MaciekzP** [muppet3000/homeassistant-growatt_server_api#25]
**Describe the bug**

When adding PV production in energy dashboard only "Lifetime energy output" entity is displayed.
**To Reproduce**

1. Go to settings ==> dashboards
2. Click energy dahsboard
3. In PV section (top right) click "add PV production. Scroll down list of entieties will be displayed.
4. The only visible entieties visible from growatt integrations are "Lifetime energy output" but would expect "Output power"
**Growatt Device Type**

Device(s):  Inverter

**Home Assistant information**
 - Home Assistant version: Home Assistant 2023.2.3
 - Growatt Server API Integration version: Latest

**Additional context**

[https://developers.home-assistant.io/docs/core/entity/sensor/#long-term-statistics](url)

**Comment by muppet3000** [comment]
Please can you use the template that is pre-populated for bug fixes. It provides all of the relevant information required to investigate and fix problems.
Without that template being populated I will be unable to progress this bug.

**Comment by muppet3000** [comment]
I've looked through the code, this is correct behaviour.

I think you're misunderstanding how the Energy Dashboard works in Home Assistant.

It doesn't work by taking the kW or W output of a device and then calculating the kWh from that. Instead it takes a running total of the kWh and then aggregates it/separates it over time.

If you select that value I can promise you it'll give you the expected result.
