### ISSUE TITLE
BUG - Plant renamed to "alias"

### ISSUE THREAD

**Issue by Saentist** [muppet3000/homeassistant-growatt_server_api#3]
After HA restart now plant name is renamed to "alias"

**Comment by muppet3000** [comment]
@Saentist I've just logged into https://server.growatt.com using the credentials you gave me a while back. 
The plugin pulls the names of the plant and inverters from the server directly, the inverter is called "alias" in the Growatt UI:

![image](https://user-images.githubusercontent.com/10612068/212939782-3855b601-d28e-4ce9-9bf6-08590506d4c1.png)

Did you change it recently??

This is definitely not a bug in the integration.

**Comment by Saentist** [comment]
Not changed by me, I use user account and no one use admin account with is strange.
and all HA graphs are gone for last days.

Guess someone have greatest idea to exclude non Latin letters i names.

**Comment by muppet3000** [comment]
Have you tried naming it back to what it was before? Either way, this isn't a problem with the Integration it's just pulling the values from the server.

**Comment by Saentist** [comment]
Yes I rename it and all entities light as normal on embeded.
but on 1.1 need removing...

**Comment by muppet3000** [comment]
It should work the same with this integration as well, the code is identical

**Comment by Saentist** [comment]
different naming
v1.1
```
sensor.home_total_total_money_today_2
sensor.alias_ac_frequency
```

embeded
```
sensor.home_total_total_money_today
sensor.pokriv_ac_frequency
```

**Comment by muppet3000** [comment]
Ahhh that would have happened if you were trying to use both integrations at the same time, they provide the same values so you can't have them both running at the same time.
