### ISSUE TITLE
ENCHANCEMENT - Energy sensors/metrics as statistics

### ISSUE THREAD

**Issue by pmp02** [muppet3000/homeassistant-growatt_server_api#30]
**Is your feature request related to a problem? Please describe.**
I want to add the Energy Today sensor value to the Energy Dashboard but it's not listed. Only the Lifetime energy (which is not accurate) is available in the dropdown. 
I do not have the Inverter values working (yet, as I have an MAX/MID/MAC inverter which is not yet supported), so only few at the farm level.

**Describe the solution you'd like**
All sensors which gather energy (kWh) to be defined as statistic (as per [HA request](https://www.home-assistant.io/more-info/statistics/)

**Describe alternatives you've considered**
Currently using the Lifetime Energy sensor in the Energy dashboard but it's not that accurate (I don't thing Growatt is calculating it that often).

**Additional context**
You can see difference shown in the Energy Dashboard (calculated from Lifetime energy) vs Energy Today from the Growatt integration.

![Energy_dashboard](https://user-images.githubusercontent.com/62330374/231127219-e21f156b-0ebc-48a4-a903-020c95218d76.png)

**Comment by bardahlm** [comment]
The energy dashboard is updated only once per hour.

**Comment by muppet3000** [comment]
Hi @pmp02 I've just pushed a change to the 'dev' branch so that the "Energy Today" field should appear on the Energy Dashboard. Let me know how it performs.

**Comment by pmp02** [comment]
Hi @muppet3000 !
Growatt has locked my account, so I'm waiting for them to unlock it, create another user and then give it a try.

Thanks a lot, that was fast :).

**Comment by muppet3000** [comment]
@pmp02 - Have you tried just creating another account through the web UI?
You can follow my instructions here: https://github.com/muppet3000/homeassistant-growatt_server_api/blob/dev/FAQ.md#how-do-i-share-my-credentials-with-you-for-testingadding-new-features-for-my-system-type

**Comment by pmp02** [comment]
Thanks @muppet3000 , I've seen the steps but didn't got the time do it. Will give it a try the following days.

**Comment by pmp02** [comment]
Hi, @muppet3000 . Just tried the new version and the statistic works! Nice! Thanks a lot!

**Comment by muppet3000** [comment]
No problem, happy to help

**Comment by IlPicasso** [comment]
Hello , this doesnt seems to be working well 
![Screenshot_2023-07-17-20-56-14-805_io homeassistant companion android](https://github.com/muppet3000/homeassistant-growatt_server_api/assets/5110242/0a530b29-47b1-41e4-a34e-9b2d3c63a8b4)

**Comment by Saentist** [comment]
> Hello , this doesnt seems to be working well 
Too many restart's of integration, and ban from server.
24h patience without access.

**Comment by IlPicasso** [comment]
> > Hello , this doesnt seems to be working well
> 
> Too many restart's of integration, and ban from server. 24h patience without access.

I just moved to grott! Best decision

**Comment by muppet3000** [comment]
> > > Hello , this doesnt seems to be working well
> > 
> > 
> > Too many restart's of integration, and ban from server. 24h patience without access.
> 
> I just moved to grott! Best decision

Correct answer!!!

Did you use my other integration? https://github.com/muppet3000/homeassistant-grott
