### ISSUE TITLE
Battery charge/discharge today can't be used on the Energy Dashboard

### ISSUE THREAD

**Issue by xhemp** [muppet3000/homeassistant-growatt_server_api#34]
I posted this on the HA thread (Roadmap) but I think it's better suitable here than there.
I am trying to refrain from using the grott_ha.py and only use this integration but HA doesn’t allow me to use the battery_charged_today and battery_discharged_today on the energy dashboard. I am just wondering if it’s because their state_class are set to TOTAL instead of TOTAL_INCREASING as the ones that being used on the grott_ha.py ?

Device(s):  SPA3000

 - Home Assistant version: 2023.6.2 
 - Growatt Server API Integration version:  Latest

**Comment by muppet3000** [comment]
Ignore Grott HA, use this instead: https://github.com/muppet3000/homeassistant-grott

Let me know how you get on, I'm trying to steer everyone towards that instead.

**Comment by xhemp** [comment]
Ahh, that's the one I am using! :)
I can open this issue there instead of here, though, let me know.

**Comment by muppet3000** [comment]
I recommend taking a read of this discussion: https://github.com/muppet3000/homeassistant-grott/issues/16

If you used the egguy add-on to install grott you're almost certainly seeing the same issue as snux. 

Assuming you're seeing the same issues let's continue the discussion over there and close this one off as it's not related to this integration.

**Comment by xhemp** [comment]
I am looking at this (it looks like it's the same issue and if not exactly the same, very similar)  and see if I could figure it out, will update if I do (or don't!), thanks for the help!

**Comment by xhemp** [comment]
Just to confirm: I managed to go through anything I had on my configuration.yaml and then the mqtt devices with growatt or coming from egguy's plugin, deleted them all, restarted HA and managed to get  it all working (battery/charge/discharge on the energy dashboard working fine).
