### ISSUE TITLE
FR - Change values icons

### ISSUE THREAD

**Issue by Saentist** [muppet3000/homeassistant-growatt_server_api#6]
Because not enabled discussions in repo.

Is it possible to be replaced icons of values 
https://materialdesignicons.com
![image](https://user-images.githubusercontent.com/16975883/212096783-7eae5907-7bc6-4372-bf0c-3346eb1f0fc6.png)
![image](https://user-images.githubusercontent.com/16975883/212096939-d147e5ac-e244-4373-8ad4-8622013a9b73.png)
![image](https://user-images.githubusercontent.com/16975883/212097234-9ca63ce1-65f3-4203-b6cb-754ea3d21fe5.png)

**Comment by muppet3000** [comment]
Hi @Saentist - I haven't got around to enabling discussions yet. I'll do it in the future.
We/I have no say over the icons that are available in Home Assistant, especially on a per-integration basis. Sorry.

**Comment by muppet3000** [comment]
I'll take a look when I next go near the sensor code, thank you for the snippet.
Since this is just a cosmetic change it will be lower priority to implement vs bug fixes and missing functionality.

**Comment by muppet3000** [comment]
Given the fact that the Growatt API is increasingly unreliable (see #15) I have slowly winding down support for this repo and instead directing people towards trying Grott instead: https://github.com/muppet3000/homeassistant-grott

I'm happy to help people out migrating over to the new method, it's far more reliable and I'm focussing all my efforts into making it the best possible option for everyone (including feeding back changes to the main developer)
